inputDir: /home/snikoletos/simpathicv3
lastUpdate: 2024/01/31
keywords: Brain Diseases, Metabolic
mongodb: {host: 143.233.226.92, port: 27017, dbname: simpathic3}
pathDelimiter: /
rabbitmq: {host: localhost, port: 5672, username: guest, password: guest, exchange: iasis.direct,
  routingkeyListen: iasis.literature_harvester.routingkey, queueListen: iasis.literature_harvester.queue,
  routingkeySent: iasis.orchestrator.routingkey, queueSent: iasis.orchestrator.queue,
  modulename: literature_harvester}
